CREATE USER t4adt WITH PASSWORD 't4adt';
CREATE DATABASE t4adt owner t4adt;
GRANT ALL ON DATABASE t4adt to t4adt;

\c t4adt

CREATE TABLE MSG_HISTORY (id VARCHAR(100), TYPE VARCHAR(10), timestamp VARCHAR(100), data TEXT);
CREATE TABLE FAIL_MSG_HISTORY (id VARCHAR(100), TYPE VARCHAR(10), timestamp VARCHAR(100), exception TEXT, data TEXT);
CREATE TABLE CAMEL_MESSAGEPROCESSED (processorName VARCHAR(255), messageId VARCHAR(100), createdAt TIMESTAMP);

ALTER TABLE MSG_HISTORY OWNER TO t4adt;
ALTER TABLE FAIL_MSG_HISTORY OWNER TO t4adt;
ALTER TABLE CAMEL_MESSAGEPROCESSED OWNER TO t4adt;

