CREATE USER nhadt WITH PASSWORD 'nhadt';
CREATE DATABASE nhadt owner nhadt;
GRANT ALL ON DATABASE nhadt to nhadt;

\c nhadt

CREATE TABLE MSG_HISTORY (id TEXT, TYPE VARCHAR(10), HOSPITAL_NUMBER TEXT, VISIT_ID TEXT,timestamp VARCHAR(100), data TEXT);
CREATE TABLE FAIL_MSG_HISTORY (id TEXT, TYPE VARCHAR(10), HOSPITAL_NUMBER TEXT, VISIT_ID TEXT, timestamp VARCHAR(100), exception TEXT, data TEXT);

ALTER TABLE MSG_HISTORY OWNER TO nhadt;
ALTER TABLE FAIL_MSG_HISTORY OWNER TO nhadt;

