\c t4adt

ALTER TABLE MSG_HISTORY RENAME TO MSG_HISTORY_OLD;
ALTER TABLE FAIL_MSG_HISTORY RENAME TO FAIL_MSG_HISTORY_OLD;

CREATE TABLE MSG_HISTORY (id TEXT, TYPE VARCHAR(10), HOSPITAL_NUMBER TEXT, VISIT_ID TEXT,timestamp VARCHAR(100), data TEXT);
CREATE TABLE FAIL_MSG_HISTORY (id TEXT, TYPE VARCHAR(10), HOSPITAL_NUMBER TEXT, VISIT_ID TEXT, timestamp VARCHAR(100), exception TEXT, data TEXT);

ALTER TABLE MSG_HISTORY OWNER TO t4adt;
ALTER TABLE FAIL_MSG_HISTORY OWNER TO t4adt;
