version: "2"
services:
  adt-connector:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - 8888:8888
    links:
      - db-adt
    # Environment variables based on the values in setupPGSQLForAdt.sql
    environment:
      - USER=nhadt
      - PASSWORD=nhadt
      - HOST=db-adt

  db-adt:
    image: postgres:9.3
    volumes:
      - "/home/liveobs/BJSS_liveobs_adt_connector/setupPGSQLForAdt.sql:/docker-entrypoint-initdb.d/setupPGSQLForAdt.sql"

  adminer:
    image: adminer
    ports:
      - 8080:8080
