version: "2"
services:
  adt-connector:
    container_name: adt-connector
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - 8888:8888
    links:
      - db-adt
    # Environment variables based on the values in setupPGSQLForAdt.sql
    environment:
      - USER=nhadt
      - PASSWORD=nhadt
      - HOST=db-adt

  db-adt:
    container_name: db-adt
    image: postgres:9.3
    volumes:
      - "../setupPGSQLForAdt.sql:/docker-entrypoint-initdb.d/setupPGSQLForAdt.sql"
    links:
      - redis

  redis:
    image: redis
    container_name: redis-adt
    ports:
      - "6379:6379"

  adminer:
    container_name: adminer-adt
    image: adminer
    ports:
      - 8080:8080
