#!/bin/bash
if [[ -z "${GO_ENVIRONMENT_NAME}" ]]; then
    echo "local-build"
else
    version=$(echo $GO_SCM_ADT_CONNECTOR_GITHUB_PR_BRANCH | sed 's/bjss://')
    build_number=_$GO_PIPELINE_COUNTER
    docker_tag=$version$build_number
    echo $docker_tag
fi
